version: '3'

networks:
  app-tier:
    driver: bridge

    
services:
  queue:
    build: rbmq/.
    container_name: rabbitmq
    ports:
      - 5672:5672 
      - 15672:15672
    networks:
      - app-tier  